[package]
name = "rustytele"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
byteorder = "1.5.0"
lazy_static = "1.5.0"
md5 = "0.7.0"
pbkdf2 = "0.12.2"
rusqlite = {version = "0.32.1", featuers = ["bundled"]}
sha1 = "0.10.6"
sha2 = "0.10.8"

